// HTML selection
const elRuleImg = document.getElementById("ruleImg"),
  elLoader = document.getElementById("loader"),
  elLogo = document.getElementById("logo"),
  elScore = document.getElementById("score"),
  elModeChangerButton = document.getElementById("modeChangerButton"),
  elGameMode = document.getElementById("gameMode"),
  elHands = document.querySelectorAll(".js-hand"),
  elHandImages = document.querySelectorAll(".js-hand-image"),
  elRule = document.getElementById("rule"),
  elRuleButton = document.getElementById("ruleButton"),
  elChoosingZone = document.getElementById("choosingZone"),
  elGamingZone = document.getElementById("gamingZone"),
  elPickedHandUserImg = document.getElementById("pickedHandUserImg"),
  elPickedHandRobotImg = document.getElementById("pickedHandRobotImg"),
  elStatusContainer = document.getElementById("statusContainer"),
  elStatusText = document.getElementById("statusText"),
  elResetGameButton = document.getElementById("resetGameButton"),
  origin = location?.origin,
  html = document.documentElement;

export {
  elLoader,
  elRuleImg,
  elRule,
  elRuleButton,
  elLogo,
  elScore,
  elModeChangerButton,
  elGameMode,
  elHands,
  elHandImages,
  elChoosingZone,
  elGamingZone,
  elPickedHandUserImg,
  elPickedHandRobotImg,
  elStatusContainer,
  elStatusText,
  elResetGameButton,
  origin,
  html,
};
